admin_carriers_index:
  path: /
  methods: GET
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Improve\Shipping\CarrierController::indexAction'
    _legacy_controller: AdminCarriers
    _legacy_link: AdminCarriers
    _legacy_feature_flag: carrier

admin_carriers_search:
  path: /
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Improve\Shipping\CarrierController::searchAction'
    _legacy_controller: AdminCarriers
    _legacy_link: AdminCarriers:submitFiltercarrier
    _legacy_feature_flag: carrier

admin_carriers_create:
  path: /create
  methods: [ GET, POST ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Improve\Shipping\CarrierController::createAction'
    _legacy_controller: AdminCarriers
    _legacy_link: AdminCarriers:addcarrier
    _legacy_feature_flag: carrier

admin_carriers_edit:
  path: /{carrierId}/edit
  methods: [ GET, POST ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Improve\Shipping\CarrierController::editAction'
    _legacy_controller: AdminCarriers
    _legacy_link: AdminCarriers:updatecarrier
    _legacy_feature_flag: carrier
  requirements:
    carrierId: \d+

admin_carriers_delete:
  path: /{carrierId}/delete
  methods: [ POST, DELETE ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Improve\Shipping\CarrierController::deleteAction'
    _legacy_controller: AdminCarriers
    _legacy_link: AdminCarriers:deletecarrier
    _legacy_feature_flag: carrier
    _legacy_parameters:
      id_carrier: carrierId
  requirements:
    carrierId: \d+

admin_carriers_toggle_status:
  path: /{carrierId}/toggle-status
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Improve\Shipping\CarrierController::toggleStatusAction'
    _legacy_controller: AdminCarriers
    _legacy_link: AdminCarriers:statuscarrier
    _legacy_feature_flag: carrier
    _legacy_parameters:
      id_carrier: carrierId
  requirements:
    carrierId: \d+

admin_carriers_toggle_is_free:
  path: /{carrierId}/toggle-is-free
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Improve\Shipping\CarrierController::toggleIsFreeAction'
    _legacy_controller: AdminCarriers
    _legacy_link: AdminCarriers:isFreecarrier
    _legacy_feature_flag: carrier
    _legacy_parameters:
      id_carrier: carrierId
  requirements:
    carrierId: \d+

admin_carriers_update_position:
  path: /update-position
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Improve\Shipping\CarrierController::updatePositionAction'
    _legacy_controller: AdminCarriers
    _legacy_link: AdminCarriers:updatePositions
    _legacy_feature_flag: carrier

admin_carriers_bulk_enable_status:
  path: /bulk-enable
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Improve\Shipping\CarrierController::bulkEnableStatusAction'
    _legacy_controller: AdminCarriers
    _legacy_link: AdminCarriers:submitBulkenableSelectioncarrier
    _legacy_feature_flag: carrier

admin_carriers_bulk_disable_status:
  path: /bulk-disable
  methods: POST
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Improve\Shipping\CarrierController::bulkDisableStatusAction'
    _legacy_controller: AdminCarriers
    _legacy_link: AdminCarriers:submitBulkdisableSelectioncarrier
    _legacy_feature_flag: carrier

admin_carriers_bulk_delete:
  path: /bulk-delete
  methods: [ POST, DELETE ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Improve\Shipping\CarrierController::bulkDeleteAction'
    _legacy_controller: AdminCarriers
    _legacy_link: AdminCarriers:submitBulkdeletecarrier
    _legacy_feature_flag: carrier
