services:
  _defaults:
    public: true

  doctrine.cache.adapter:
    class: Symfony\Component\Cache\Adapter\FilesystemAdapter
    arguments:
      - ''
      - 0
      - "%kernel.cache_dir%/doctrine"

  doctrine.cache.provider:
    class: Doctrine\Common\Cache\Psr6\DoctrineProvider
    factory: [ Doctrine\Common\Cache\Psr6\DoctrineProvider, wrap ]
    arguments:
      - "@doctrine.cache.adapter"

  main.warmer.cache_warmer:
    class: PrestaShopBundle\Cache\CacheWarmer
    arguments:
      - "@filesystem"
    tags:
      - { name: kernel.cache_warmer }

  PrestaShopBundle\Cache\LegacyCacheClearer:
    autowire: true
    autoconfigure: true
    arguments:
      $legacyCacheDir: '%prestashop.legacy_cache_dir%'
