services:
  _defaults:
    public: true

  PrestaShopBundle\Command\UpdateSchemaCommand:
    arguments:
      - '%database_name%'
      - '%database_prefix%'
      - '@doctrine.orm.default_entity_manager'
    tags:
      - 'console.command'

  PrestaShopBundle\Command\ExportThemeCommand:
    arguments:
      - '@prestashop.core.addon.theme.repository'
      - '@prestashop.core.addon.theme.exporter'
      - '@translator'
    tags:
      - 'console.command'

  PrestaShopBundle\Command\GenerateMailTemplatesCommand:
    arguments:
      - '@prestashop.core.command_bus'
      - '@prestashop.adapter.legacy.context'
    tags:
      - 'console.command'

  PrestaShopBundle\Command\ThemeEnablerCommand:
    arguments:
      - '@prestashop.core.addon.theme.theme_manager'
    tags:
      - 'console.command'

  PrestaShopBundle\Command\UpdateEUTaxruleGroupsCommand:
    arguments:
      - '%kernel.project_dir%/localization'
    tags:
      - 'console.command'

  PrestaShopBundle\Command\ModuleCommand:
    autowire: true
    tags:
      - 'console.command'

  PrestaShopBundle\Command\DebugCommand:
    arguments:
      - '@prestashop.core.command_bus'
      - '@prestashop.adapter.debug_mode'
    tags:
      - 'console.command'

  PrestaShopBundle\Command\ConfigCommand:
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - '@prestashop.adapter.data_provider.language'
    tags:
      - 'console.command'

  PrestaShopBundle\Command\FeatureFlagCommand:
    autowire: true
    tags:
      - 'console.command'

  PrestaShopBundle\Command\GenerateAPIDocCommand:
    autowire: true
    tags:
      - 'console.command'

  PrestaShopBundle\Command\GenerateHooksDocumentationCommand:
    arguments:
      - '@prestashop.core.hook.extractor.hook_extractor'
      - '%kernel.project_dir%/install-dev/data/xml/hook.xml'
    tags:
      - 'console.command'

  PrestaShopBundle\Command\AboutCommand:
    arguments:
      - '@prestashop.adapter.legacy.configuration'
    tags:
      - 'console.command'

  PrestaShopBundle\Command\ExportModuleTranslationsCommand:
    arguments:
      $translationCatalogueExporter: '@prestashop.translation.export.translation_catalogue'
      $filesystem: '@filesystem'
      $moduleDir: '%prestashop.module_dir%'
    tags:
      - 'console.command'

  PrestaShopBundle\Command\SearchIndexationCommand:
    arguments:
      - '@prestashop.core.command_bus'
    tags:
      - 'console.command'

  PrestaShopBundle\Command\RegenerateThumbnailsCommand:
    arguments:
      - '@prestashop.core.command_bus'
    tags:
      - 'console.command'
