imports:
  - { resource: ./circuit_breaker.yml }
  - { resource: ./feature_flag.yml }

services:
  PrestaShop\PrestaShop\Core\EnvironmentInterface:
    alias: prestashop.adapter.environment

  PrestaShop\PrestaShop\Core\Crypto\Hashing: ~
  prestashop.core.crypto.hashing:
    alias: PrestaShop\PrestaShop\Core\Crypto\Hashing

  PrestaShop\PrestaShop\Core\Security\Hashing: ~

  PrestaShop\PrestaShop\Core\Hook\HookModuleFilter:
    public: true
    arguments:
      - !tagged core.hook_module_exec_filter
