services:
  _defaults:
    public: true

  PrestaShop\PrestaShop\Adapter\Configuration: ~

  prestashop.adapter.legacy.configuration:
    alias: PrestaShop\PrestaShop\Adapter\Configuration

  PrestaShop\PrestaShop\Adapter\Tools: ~

  prestashop.adapter.tools:
    alias: PrestaShop\PrestaShop\Adapter\Tools
    deprecated:
      package: PrestaShop\PrestaShop
      version: 8.1

  PrestaShop\PrestaShop\Adapter\LegacyContext:
    arguments:
      - "%mail_themes_uri%"
      - '@PrestaShop\PrestaShop\Adapter\Tools'

  PrestaShop\PrestaShop\Adapter\Shipment\OrderShipmentCreator:
    arguments:
      - '@PrestaShopBundle\Entity\Repository\ShipmentRepository'

  prestashop.adapter.legacy.context:
    alias: PrestaShop\PrestaShop\Adapter\LegacyContext

  prestashop.adapter.environment:
    class: PrestaShop\PrestaShop\Adapter\Environment
    arguments:
      $isDebug: '%kernel.debug%'
      $name: '%kernel.environment%'
      $appId: '%kernel.app_id%'

  prestashop.adapter.validate:
    class: PrestaShop\PrestaShop\Adapter\Validate

  PrestaShop\PrestaShop\Adapter\ContextStateManager:
    arguments:
      - '@PrestaShop\PrestaShop\Adapter\LegacyContext'

  prestashop.adapter.context_state_manager:
    alias: PrestaShop\PrestaShop\Adapter\ContextStateManager

  PrestaShop\PrestaShop\Adapter\Employee\EmployeeRepository: ~

  prestashop.adapter.employee_language_updater:
    class: PrestaShop\PrestaShop\Adapter\Employee\EmployeeLanguageUpdater
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
      - '@=service("prestashop.adapter.legacy.configuration").get("PS_LANG_DEFAULT")'

  PrestaShop\PrestaShop\Adapter\Bundle\AssetsInstaller:
    class: PrestaShop\PrestaShop\Adapter\Bundle\AssetsInstaller
