services:
  _defaults:
    public: true

  # Command Handlers
  prestashop.adapter.search.command_handler.index_search_handler:
    class: PrestaShop\PrestaShop\Adapter\Search\CommandHandler\SearchIndexationHandler
    autowire: true
    autoconfigure: true
